name: sea_weather_app
description: Consulta el tiempo y el estado del mar en tus playas y calas favoritas.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: ^8.3.1
  font_awesome_flutter: ^11.0.0
  http: ^1.6.0
  latlong2: ^0.10.1
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: ".github/images/logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#00D3FF"
  adaptive_icon_foreground: ".github/images/logo.png"
  macos:
    generate: true
    image_path: ".github/images/logo.png"
  windows:
    generate: true
    image_path: ".github/images/logo.png"
  web:
    generate: true
    image_path: ".github/images/logo.png"
